## 2.4 Pandas 入門
演習問題解答例

In [1]:
# 日本語化ライブラリ導入
!pip install japanize-matplotlib | tail -n 1

Successfully installed japanize-matplotlib-1.1.3

In [2]:
# 事前処理

# 必要ライブラリのimport
import numpy as np

# Matplotlib中のpyplotライブラリのインポート
import matplotlib.pyplot as plt

# matplotlib日本語化対応ライブラリのインポート
import japanize_matplotlib

In [3]:
# NumPy表示形式の設定
np.set_printoptions(
    suppress=True, precision=4, floatmode='fixed'
)

# グラフのデフォルトフォント指定
plt.rcParams["font.size"] = 14

# サイズ設定
plt.rcParams['figure.figsize'] = (6, 6)

In [4]:
# ライブラリのインポート

# pandas用ライブラリ
import pandas as pd

# データフレーム表示用関数
from IPython.display import display

In [5]:
# パラメータ初期化

# データフレームでの表示精度
pd.options.display.float_format = '{:.4f}'.format

# データフレームですべての項目を表示
pd.set_option("display.max_columns",None)

### 演習問題
 (1)
次のような変数data1, data2, columnsが定義されているとき、この変数を使って、データフレーム変数df1とdf2を定義して下さい。  
data1とdata2はデータフレームのデータに該当する部分、columnsは項目名のリストとします。

```
data1 = [
['田中優花' ,'女', 140, 40.5],
['佐藤和也', '男', 175, 70.2],
]
data2 = [
['鈴木一郎', '男', 170, 65.0],
['高橋美香', '女', 158, 55.6]
]
columns=['氏名', '性別', '身長', '体重']
```

(2) 
df1とdf2をタテ方向に連結して、新しいデータフレームdf3を作りなさい。

In [6]:
# 初期データの宣言
data1 = [
['田中優花' ,'女', 140, 40.5],
['佐藤和也', '男', 175, 70.2],
]

data2 = [
['鈴木一郎', '男', 170, 65.0],
['高橋美香', '女', 158, 55.6]
]

columns=['氏名', '性別', '身長', '体重']

In [9]:
# (1)の解答
# 2.4.3節　コード2-4-4 参照　
df1 = pd.DataFrame(data1, columns=columns)
df2 = pd.DataFrame(data2, columns=columns)

# (1)の結果確認
display(df1)
display(df2)

     氏名 性別   身長      体重
0  田中優花  女  140 40.5000
1  佐藤和也  男  175 70.2000

     氏名 性別   身長      体重
0  鈴木一郎  男  170 65.0000
1  高橋美香  女  158 55.6000

In [10]:
# (2)の解答
# 2.4.5節  コード2-4-28 及び図2-4-3参照
# ignore_indexオプションは2.4.5節　コード2-4-29参照
df3 = pd.concat(
    [df1, df2], axis=0, 
    ignore_index=True)

# (2)の結果確認
display(df3)

     氏名 性別   身長      体重
0  田中優花  女  140 40.5000
1  佐藤和也  男  175 70.2000
2  鈴木一郎  男  170 65.0000
3  高橋美香  女  158 55.6000